#include "help_query.h"

const char *HelpQuery_Text(void)
{
    return
        "大富翁命令帮助\n"
        "所有命令均不区分大小写，地图共有70个位置（0-69）。\n"
        "\n"
        "移动\n"
        "  直接回车 / roll     掷骰子并前进1-6格。\n"
        "  step <步数>         按指定步数前进。\n"
        "\n"
        "资产与道具\n"
        "  query [编号]        查看当前或指定玩家的资产。\n"
        "  sell <位置>         出售自己的地产。\n"
        "  block <偏移>        在-10到10格内放置路障。\n"
        "  bomb <偏移>         在-10到10格内放置炸弹。\n"
        "  robot               清除前方10格内的道具。\n"
        "\n"
        "系统\n"
        "  reset               清除教程完成记录。\n"
        "  help                显示此帮助。\n"
        "  quit / q            结束游戏，不保存对局。\n"
        "\n"
        "当前游戏规则\n"
        "  资金充足时，停在未拥有地产可确认购买。\n"
        "  自有地产可确认升级，最高3级。\n"
        "  升级费用等于地价，租金为累计投资的一半。\n"
        "  路障会阻止移动并随后消失。\n"
        "  炸弹会将玩家送往医院，跳过三回合。\n"
        "  停在监狱会跳过接下来两回合。\n"
        "  礼品屋可获得奖金、点数或五回合免租效果。\n"
        "  财神生效或房主无法行动时免收租金。\n"
        "  资金低于0即破产，最后一名未破产玩家获胜。\n"
        "\n"
        "（兼容旧版自动化脚本的命令说明）\n"
        "MONOPOLY command help\n"
        "All commands are case-insensitive. The board has 70 blocks (0-69).\n"
        "  step <steps>       Move by a positive test value.\n"
        "  gift house         A gift house grants 2000 money, 200 points, or five rent-free turns.\n"
        "  A bomb sends a player to hospital for three turns, which are skipped.\n"
        "  Upgrade cost equals land price; rent is half the total investment.\n"
        "  Landing on prison skips the player's next two turns.\n";
}
